### ISSUE TITLE
Unable to submit custom streaming jobs to EMR

### ISSUE THREAD

**Issue by mdagost** [aws/aws-cli#1453]
I'm trying to submit a streaming job with a custom python mapper and reducer.  However, the AWS CLI is not properly parsing the arguments as they are passed into hadoop.  Here is my command (simplified without real file locations):

```
aws emr add-steps --cluster-id j-XXXX --steps Type=STREAMING,Name='My Job',ActionOnFailure=CONTINUE,Args=[-files,"s3://map-simple.py,s3://reduce-simple.py,s3://additional-file",-mapper,map-simple.py,-reducer,reduce-simple.py,-input,s3://in/,-output,s3://out/]
```

This is translated into the following hadoop command in the EMR logs:

```
bash /usr/lib/hadoop/bin/hadoop jar /var/lib/aws/emr/step-runner/hadoop-jars/command-runner.jar hadoop-streaming -files s3://map-simple.py s3://reduce-simple.py s3://additional-file -mapper map-simple.py -reducer reduce-simple.py -input s3://in/ -output s3://out/
```

Notice that it has inserted spaces between the s3 files to the "-files" argument.  The documentation says that, to pass multiple files, they must be separated by commas.  I have verified by logging into the master that the following command does work:

```
bash /usr/lib/hadoop/bin/hadoop jar /var/lib/aws/emr/step-runner/hadoop-jars/command-runner.jar hadoop-streaming -files s3://map-simple.py,s3://reduce-simple.py,s3://additional-file -mapper map-simple.py -reducer reduce-simple.py -input s3://in/ -output s3://out/
```

So the AWS CLI is stripping out those commas that need to be there.  I've tried escaping it in multiple ways, but nothing seems to work.  This is high severity because, as far as I can tell, there's no way to submit a streaming job with a custom mapper and a custom reducer using the AWS CLI at this time.

**Comment by rayluo** [comment]
Gonna test this

**Comment by mdagost** [comment]
@rayluo AWS support has verified this on their end.

**Comment by jamesls** [comment]
This should be fixed in the latest version of the CLI.  Can you confirm if you still this issue on v1.8.6 or greater?

**Comment by yusufcangurkan** [comment]
Hello, is this bug fixed on latest AWS CLI because im still getting same problem on latest one.

**Comment by mdagost** [comment]
I haven't tried to verify one way or the other...

**Comment by Puriney** [comment]
Hi, the bug still exists

**Comment by jgustave** [comment]
Still there in 1.16.173
