### ISSUE TITLE
Error in cloudformation create-stack documentation

### ISSUE THREAD

**Issue by iainelder** [aws/aws-cli#2383]
Using `aws-cli/1.11.36 Python/2.7.13 Darwin/16.3.0 botocore/1.4.93`.

Run this command in Mac OS X Terminal to view the cloudformation create-stack documentation.

```
aws cloudformation create-stack help
```

Press `q` to quit the viewer.

This error appears in the terminal.

```
<string>:193: (WARNING/2) Inline literal start-string without end-string.
```

There is no obvious problem with the documentation, but the error is distracting in any case.

**Comment by lankygit** [comment]
Confirmed on Windows and Linux clients and for an older version 
```
~$ aws cloudformation create-stack help
<string>:189: (WARNING/2) Inline literal start-string without end-string.
~$ aws --version
aws-cli/1.10.58 Python/2.7.6 Linux/3.13.0-106-generic botocore/1.4.48

```

**Comment by kyleknap** [comment]
I can confirm. I have seen this in other commands as well that have bold/italicized elements inside of literal elements. It is related to our doc/help page render. We look to see what we can do to fix that.

**Comment by andreouelletbni** [comment]
I am running into the same issue when running **aws cloudformation create-stack help**

I found a link to a bug issue of same nature where this was fixed for python itself.
There is link to patch where this is fixed   --> https://bugs.python.org/issue21219

Perhaps the patch fix there can help shed light on fixing this for aws cli ?

Error message on current version of aws cli on Ubuntu Linux

```
#$ aws cloudformation create-stack help
<string>:228: (WARNING/2) Inline literal start-string without end-string.

#$ aws --version
aws-cli/1.14.6 Python/3.5.2 Linux/4.4.0-101-generic botocore/1.8.10

#$  lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

#$  uname -a
Linux bni7kc89ee 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lazize** [comment]
I can confirm this still happening, see the debug log below:

```shell
$ aws cloudformation create-stack help --debug
2019-07-22 10:21:13,151 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.202 Python/3.7.3 Linux/5.0.0-20-generic botocore/1.12.192
2019-07-22 10:21:13,152 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudformation', 'create-stack', 'help', '--debug']
2019-07-22 10:21:13,152 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fe042dae400>
2019-07-22 10:21:13,152 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fe043533840>
2019-07-22 10:21:13,153 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fe0434e7d08>
2019-07-22 10:21:13,157 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fe042ef5620>
2019-07-22 10:21:13,159 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.7/dist-packages/botocore/data/cloudformation/2010-05-15/service-2.json
2019-07-22 10:21:13,163 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function inject_commands at 0x7fe0434f9048>
2019-07-22 10:21:13,163 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function add_waiters at 0x7fe042db3950>
2019-07-22 10:21:13,171 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.7/dist-packages/botocore/data/cloudformation/2010-05-15/waiters-2.json
2019-07-22 10:21:13,173 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('stack-name', <awscli.arguments.CLIArgument object at 0x7fe042c53080>), ('template-body', <awscli.arguments.CLIArgument object at 0x7fe042c625c0>), ('template-url', <awscli.arguments.CLIArgument object at 0x7fe042c625f8>), ('parameters', <awscli.arguments.ListArgument object at 0x7fe042c62630>), ('disable-rollback', <awscli.arguments.BooleanArgument object at 0x7fe042c62668>), ('no-disable-rollback', <awscli.arguments.BooleanArgument object at 0x7fe042c626a0>), ('rollback-configuration', <awscli.arguments.CLIArgument object at 0x7fe042c626d8>), ('timeout-in-minutes', <awscli.arguments.CLIArgument object at 0x7fe042c62710>), ('notification-arns', <awscli.arguments.ListArgument object at 0x7fe042c62748>), ('capabilities', <awscli.arguments.ListArgument object at 0x7fe042c62780>), ('resource-types', <awscli.arguments.ListArgument object at 0x7fe042c627b8>), ('role-arn', <awscli.arguments.CLIArgument object at 0x7fe042c627f0>), ('on-failure', <awscli.arguments.CLIArgument object at 0x7fe042c62828>), ('stack-policy-body', <awscli.arguments.CLIArgument object at 0x7fe042c62860>), ('stack-policy-url', <awscli.arguments.CLIArgument object at 0x7fe042c62588>), ('tags', <awscli.arguments.ListArgument object at 0x7fe042c62940>), ('client-request-token', <awscli.arguments.CLIArgument object at 0x7fe042c628d0>), ('enable-termination-protection', <awscli.arguments.BooleanArgument object at 0x7fe042c62978>), ('no-enable-termination-protection', <awscli.arguments.BooleanArgument object at 0x7fe042c629e8>)])
2019-07-22 10:21:13,174 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.create-stack: calling handler <function add_streaming_output_arg at 0x7fe042dae950>
2019-07-22 10:21:13,174 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.create-stack: calling handler <function add_cli_input_json at 0x7fe0434f3488>
2019-07-22 10:21:13,174 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.create-stack: calling handler <function unify_paging_params at 0x7fe042e356a8>
2019-07-22 10:21:13,179 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.7/dist-packages/botocore/data/cloudformation/2010-05-15/paginators-1.json
2019-07-22 10:21:13,180 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.create-stack: calling handler <function add_generate_skeleton at 0x7fe042e91510>
2019-07-22 10:21:13,180 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudformation.create-stack: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fe042c62a20>>
2019-07-22 10:21:13,180 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudformation.create-stack: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fe042c62898>>
2019-07-22 10:21:13,183 - MainThread - botocore.hooks - DEBUG - Event doc-breadcrumbs.cloudformation.create-stack: calling handler <bound method CLIDocumentEventHandler.doc_breadcrumbs of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,184 - MainThread - botocore.hooks - DEBUG - Event doc-title.cloudformation.create-stack: calling handler <bound method CLIDocumentEventHandler.doc_title of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,184 - MainThread - botocore.hooks - DEBUG - Event doc-description.cloudformation.create-stack: calling handler <bound method OperationDocumentEventHandler.doc_description of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,184 - MainThread - botocore.hooks - DEBUG - Event doc-description.cloudformation.create-stack: calling handler <function add_paging_description at 0x7fe042e35620>
2019-07-22 10:21:13,185 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-start.cloudformation.create-stack: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,185 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.stack-name: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,185 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.template-body: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,186 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.template-url: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,186 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.parameters: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,186 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.disable-rollback: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,186 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.no-disable-rollback: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,187 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.rollback-configuration: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,187 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.timeout-in-minutes: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,187 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.notification-arns: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,187 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.capabilities: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,188 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.resource-types: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,188 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.role-arn: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,188 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.on-failure: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,188 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.stack-policy-body: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,189 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.stack-policy-url: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,190 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.tags: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,192 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.client-request-token: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,193 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.enable-termination-protection: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,193 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.no-enable-termination-protection: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,193 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.cli-input-json: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,193 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudformation.create-stack.generate-cli-skeleton: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,194 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-end.cloudformation.create-stack: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_end of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,194 - MainThread - botocore.hooks - DEBUG - Event doc-options-start.cloudformation.create-stack: calling handler <bound method CLIDocumentEventHandler.doc_options_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,194 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.stack-name: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,195 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.stack-name: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,195 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.template-body: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,196 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.template-body: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,196 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.template-url: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,196 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.template-url: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,197 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.parameters: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,197 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.parameters: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,198 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.disable-rollback: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,198 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.disable-rollback: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,198 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.no-disable-rollback: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,199 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.no-disable-rollback: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,199 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.rollback-configuration: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,199 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.rollback-configuration: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,200 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.timeout-in-minutes: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,200 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.timeout-in-minutes: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,201 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.notification-arns: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,201 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.notification-arns: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,201 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.capabilities: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,205 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.capabilities: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,206 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.resource-types: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,207 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.resource-types: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,209 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.role-arn: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,210 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.role-arn: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,211 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.on-failure: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,212 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.on-failure: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,212 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.stack-policy-body: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,213 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.stack-policy-body: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,213 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.stack-policy-url: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,213 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.stack-policy-url: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,213 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.tags: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,213 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.tags: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,214 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.client-request-token: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,214 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.client-request-token: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,214 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.enable-termination-protection: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,215 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.enable-termination-protection: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,215 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.no-enable-termination-protection: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,216 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.no-enable-termination-protection: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,216 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.cli-input-json: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,217 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.cli-input-json: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,218 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudformation.create-stack.generate-cli-skeleton: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,219 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudformation.create-stack.generate-cli-skeleton: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,219 - MainThread - botocore.hooks - DEBUG - Event doc-options-end.cloudformation.create-stack: calling handler <bound method OperationDocumentEventHandler.doc_options_end of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,220 - MainThread - botocore.hooks - DEBUG - Event doc-examples.cloudformation.create-stack: calling handler <function add_examples at 0x7fe0434e4950>
2019-07-22 10:21:13,220 - MainThread - awscli.customizations.addexamples - DEBUG - Looking for example file at: /usr/local/lib/python3.7/dist-packages/awscli/examples/cloudformation/create-stack.rst
2019-07-22 10:21:13,220 - MainThread - botocore.hooks - DEBUG - Event doc-output.cloudformation.create-stack: calling handler <bound method OperationDocumentEventHandler.doc_output of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
2019-07-22 10:21:13,221 - MainThread - botocore.hooks - DEBUG - Event doc-relateditems-start.cloudformation.create-stack: calling handler <bound method CLIDocumentEventHandler.doc_relateditems_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x7fe042bf7e48>>
<string>:269: (WARNING/2) Inline literal start-string without end-string.
2019-07-22 10:21:13,333 - MainThread - awscli.help - DEBUG - Running command: ['groff', '-m', 'man', '-T', 'ascii']
2019-07-22 10:21:13,369 - MainThread - awscli.help - DEBUG - Running command: ['less', '-R']
```

**Comment by douglasnaphas** [comment]
What appears to be the same bug, but with a slightly different error message, is present when I run `aws acm help`:

```
ACM()                                                                    ACM()



NAME
       acm -

DESCRIPTION
       Welcome to the AWS Certificate Manager (ACM) API documentation.

       You  can use ACM to manage SSL/TLS certificates for your AWS-based web-
       sites and applications. For general information about  using  ACM,  see
       the       `      AWS      Certificate      Manager      User      Guide
       http://docs.aws.amazon.com/acm/latest/userguide/
       `
       __ .

       System Message: WARNING/2 (<string>:, line 22)
              Inline interpreted text or phrase reference start-string without
              end-string.

AVAILABLE COMMANDS
       o add-tags-to-certificate

       o delete-certificate

       o describe-certificate

       o export-certificate

       o get-certificate

       o help

       o import-certificate

       o list-certificates

       o list-tags-for-certificate

       o remove-tags-from-certificate

       o request-certificate

       o resend-validation-email

       o update-certificate-options



                                                                         ACM()
(END)
```

And when the command terminates I see:
```
$ aws acm help
<string>:22: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string.
```

I'm on macOS Catalina 10.15.4. AWS/Python versions:
```
$ aws --version
aws-cli/1.15.32 Python/3.7.6 Darwin/19.4.0 botocore/1.10.32

$ python --version
Python 3.7.4
```

**Comment by stobrien89** [comment]
Confirmed issue is no longer present in either V1 or V2.  Closing— feel free to @ me with any questions!
