### ISSUE TITLE
STS Endpoint AWS CLI calls feature request

### ISSUE THREAD

**Issue by p-lobitana** [aws/aws-cli#4463]
Hi there.

Our company utilizes the Tokyo region almost always, so we've setup an STS Endpoint, in order to make connections pass through the regional endpoint (sts.ap-northeast-1.amazonaws.com) instead of the global one (sts.amazonaws.com).

However, we've found out that although direct STS API calls in the CLI (such as assume-role command) pass through PrivateLink, calls done with '--profile' as a parameter don't. For example, calling the S3 list-buckets command while defining a profile shows that the call doesn't pass through the regional endpoint. 

We've reached out to AWS Support about this and was told that this wasn't a feature in CLI yet, and that's why we'd like to request for this feature to be added in the future. Or maybe at least, can we know if the said feature is already in the works? That way we can plan out our security policies accordingly.

Thank you in advance.

**Comment by kyleknap** [comment]
Makes sense. We are looking to add a configuration option to make the CLI use the regional endpoint instead of the global one.

**Comment by llibicpep** [comment]
I'm seeing different behaviour - on an ec2 instance with attached instance profile without specifying any `--profile` - it's still always using global endpoint instead of regional:

```
aws --debug --region us-west-2 sts get-caller-identity
...
2019-09-07 03:04:12,068 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sts.amazonaws.com:443
```

I suspect issue is the same, just making sure this scenario is also covered.

**Comment by timhargreaves** [comment]
Just want to call out that this was recently fixed in the Ruby SDK, so if someone can translate the code, the heavy lifting may already be done (not sure on how aligned the two code bases are).

https://github.com/aws/aws-sdk-ruby/pull/2090

**Comment by joguSD** [comment]
A configuration flag for this was added in 1.16.266.
See: https://github.com/aws/aws-cli/commit/9ee3575e9586f395d44a3c1d45b7fd3a337fe619

**Comment by eurythmia** [comment]
with awscli-1.16.312 I'm still seeing this issue:
```
$ aws --version
aws-cli/1.16.312 Python/3.7.5 Darwin/18.7.0 botocore/1.13.48
$ env | grep AWS
$ 
```


~/.aws/config
```
[profile default]
region = us-west-2
output = json
sts_regional_endpoints = regional

[profile cn-default]
region = cn-northwest-1
output = json
sts_regional_endpoints = regional

[profile preprod]
role_arn = arn:aws:iam::<preprod account no>:role/preprod-team
source_profile = default
role_session_name = eurythmia-preprod

[profile preprod-cn]
role_arn = arn:aws-cn:iam::<cn preprod account no>:role/preprod-team
source_profile = cn-default
role_session_name = eurythmia-cn-preprod
```

my `~/.aws/credentials` file has entries for `default` and `cn-default`.

when I run `aws --profile preprod sts get-caller-identity` I get my valid user json back. same with `aws --profile cn-default sts get-caller-identity`.

When I run `aws --debug --profile preprod-cn sts get-caller-identity`, I see that it's trying to hit `sts.amazonaws.com:443`, but if I run `aws --debug --region cn-northwest-1 --profile preprod-cn sts get-caller-identity` it hits the correct sts endpoint (`sts.cn-northwest-1.amazonaws.com.cn`) and I get my user json back.

**Comment by lmunro** [comment]
Im also still seeing this in with awscli-1.16.312.  Cannot assume roles via the default sts.amazonaws.com endpoint, only works if you set AWS_STS_REGIONAL_ENDPOINTS=regional.

No vpc endpoints and internet access is enabled.

**Comment by eurythmia** [comment]
I've found that even with `AWS_STS_REGIONAL=regional` in the environment, it's still using `'client-region': 'aws-global'` in the context for the assume-role call. So, this is definitely an issue with the assume-role call being made before the full configuration has been loaded.
