### ISSUE TITLE
ec2 security-group commands not well documented

### ISSUE THREAD

**Issue by phemmer** [aws/aws-cli#743]
Figuring out how to use the commands to modify security groups is very difficult and unintuitive.

For example, my saga to delete the following rule:

```
# aws ec2 describe-security-groups --group-id sg-097c6265

{
    "SecurityGroups": [
        {
            "IpPermissions": [
                {
                    "UserIdGroupPairs": [], 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "FromPort": 8, 
                    "ToPort": -1, 
                    "IpProtocol": "icmp"
                }
...
```

----

    aws ec2 revoke-security-group-ingress --group-name ipa --protocol icmp --from-port 8 --to-port -1 --cidr 0.0.0.0/0       

    A client error (InvalidParameterValue) occurred when calling the RevokeSecurityGroupIngress operation: Invalid value 'ipa' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation.

The help page says:
```
       --group-name (string)
          [EC2-Classic, default VPC] The name of the security group.
```
I'm guessing this means it's usable on `default VPC`, but what is the difference between `default VPC` and a normal VPC?

----

Using the security group ID instead.

    # aws ec2 revoke-security-group-ingress --group-id sg-097c6265 --protocol icmp --from-port 8 --to-port -1 --cidr 0.0.0.0/0  

    A client error (InvalidParameterValue) occurred when calling the RevokeSecurityGroupIngress operation: Invalid value 'Must specify both from and to ports with ICMP.' for portRange.

...I *did* specify both 'from' and 'to' ports...

----

Ok, lets use both `--port` and `--from-port`

    # aws ec2 revoke-security-group-ingress --group-id sg-097c6265 --protocol icmp --port 8 --from-port 8 --to-port -1 --cidr 0.0.0.0/0    
                                                                                             
    A client error (InvalidPermission.NotFound) occurred when calling the RevokeSecurityGroupIngress operation: The specified rule does not exist in this security group.

...horse do do...

----

Ok, lets try `--ip-protocol`.
Though I have no clue what the difference is from `--protocol`, the output from the the describe call does show `IpProtocol`

    # aws ec2 revoke-security-group-ingress --group-id sg-097c6265 --ip-protocol icmp --port 8 --to-port -1 --cidr 0.0.0.0/0 

    A client error (InvalidParameterValue) occurred when calling the RevokeSecurityGroupIngress operation: Invalid value 'null' for protocol. VPC security group rules must specify protocols explicitly.

...nope

----

Ok, lets try both 'protocol' options.

    # aws ec2 revoke-security-group-ingress --group-id sg-097c6265 --protocol icmp --ip-protocol icmp --port 8 --to-port -1 --cidr 0.0.0.0/0 

    A client error (InvalidPermission.NotFound) occurred when calling the RevokeSecurityGroupIngress operation: The specified rule does not exist in this security group.

At this point I gave up and did it through the web console.

**Comment by jamesls** [comment]
Looks like the fix for this issue wasn't linked.  This should be fixed now.  Part of the issue here was that we were documenting legacy params that could not be combined together (i.e `--port` and `--from-port`).  We now no longer document these mutually exclusive options, and only show the preferred params.

**Comment by rushabh268** [comment]
@jamesls I am still seeing the same issue when running this command:

`aws ec2 modify-security-group-rules --group-id sg-1233456789 --security-group-rules SecurityGroupRuleId=sgr-0123344455522,SecurityGroupRule={{FromPort=3389},{ToPort=3390},{IpProtocol="tcp"},{CidrIpv4='10.1.1.5/32'}}`

`An error occurred (InvalidParameterValue) when calling the ModifySecurityGroupRules operation: Invalid value 'null' for protocol. VPC security group rules must specify protocols explicitly.`

The command is not documented properly

**Comment by jdavidbakr** [comment]
@rushabh268 did you ever get `modify-security-group-rules` to work?  I'm getting the same error and can't figure out how to resolve it.

**Comment by va2401** [comment]
Worked for me by using 

> aws ec2 modify-security-group-rules --group-id sg-xxx
   --security-group-rules "SecurityGroupRuleId=sgr-xxx,SecurityGroupRule={Description='SSH
   Test1',CidrIpv4=x.x.x.x/32,IpProtocol=tcp,FromPort=22,ToPort=22}"

[Original answer](https://stackoverflow.com/questions/70113376/aws-cli-create-script-to-add-my-ip-to-security-group)
