### ISSUE TITLE
`aws configure import --csv` Expected header 'User Name' not found yet exists in the CSV

### ISSUE THREAD

**Issue by gitaugakwa** [aws/aws-cli#7721]
### Describe the bug

Importing a configuration using the cli doesn't work. Producing an error that the expected header is not found yet is in the csv.

### Expected Behavior

Import the configuration and add the profile to the config.

### Current Behavior

PS C:\Users\DOUG> aws configure import --profile-prefix TheUnderground --csv file://"C:\Clients\TheUnderground\Credentials\Setup\Setup.csv" --debug
2023-03-04 11:56:27,304 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.11.0 Python/3.11.2 Windows/10 exe/AMD64
2023-03-04 11:56:27,306 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'import', '--profile-prefix', 'TheUnderground', '--csv', 'file://C:\\Clients\\TheUnderground\\Credentials\\Setup\\Setup.csv', '--debug']
2023-03-04 11:56:27,352 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x0000021AFB003920>
2023-03-04 11:56:27,352 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x0000021AFAE50EA0>
2023-03-04 11:56:27,353 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2023-03-04 11:56:27,353 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000021AFADAD1C0>
2023-03-04 11:56:27,354 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000021AFADD0680>
2023-03-04 11:56:27,354 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x0000021AFB011E40>
2023-03-04 11:56:27,354 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x0000021AFAE87880>
2023-03-04 11:56:27,355 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2023-03-04 11:56:27,355 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x0000021AFB011D00>
2023-03-04 11:56:27,356 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x0000021AFB0CA010>>
2023-03-04 11:56:27,357 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Apps\Amazon\AWSCLIV2\awscli\data\cli.json
2023-03-04 11:56:27,363 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x0000021AFAF59080>
2023-03-04 11:56:27,363 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x0000021AFAF593A0>
2023-03-04 11:56:27,363 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x0000021AFAF59300>
2023-03-04 11:56:27,364 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x0000021AFAF594E0>
2023-03-04 11:56:27,364 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x0000021AFAF59440>
2023-03-04 11:56:27,365 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x0000021AFB0C7400>
2023-03-04 11:56:27,366 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.11.0 Python/3.11.2 Windows/10 exe/AMD64 prompt/off
2023-03-04 11:56:27,366 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'import', '--profile-prefix', 'TheUnderground', '--csv', 'file://C:\\Clients\\TheUnderground\\Credentials\\Setup\\Setup.csv', '--debug']
2023-03-04 11:56:27,366 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x0000021AFB0102C0>
2023-03-04 11:56:27,367 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x0000021AFAB3E0C0>
2023-03-04 11:56:27,367 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x0000021AFB087240>
2023-03-04 11:56:27,368 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x0000021AFAB227A0>
2023-03-04 11:56:27,368 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x0000021AFAB939C0>
2023-03-04 11:56:27,370 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2023-03-04 11:56:27,373 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x0000021AFAE84180>
2023-03-04 11:56:27,374 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x0000021AFAE41120>
2023-03-04 11:56:27,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x0000021AFB085F80>
2023-03-04 11:56:27,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x0000021AFB011D00>
2023-03-04 11:56:27,376 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x0000021AFB0CA010>>
2023-03-04 11:56:27,377 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_import: calling handler <function add_waiters at 0x0000021AFB011D00>
2023-03-04 11:56:27,377 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_import: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x0000021AFB0CA010>>
2023-03-04 11:56:27,378 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.csv: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000021AFAB65090>
2023-03-04 11:56:27,379 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000021AFAC05650>
2023-03-04 11:56:27,379 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.skip-invalid: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000021AFAB65090>
2023-03-04 11:56:27,380 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000021AFAC05650>
2023-03-04 11:56:27,380 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.profile-prefix: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000021AFAB65090>
2023-03-04 11:56:27,381 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000021AFAC05650>
2023-03-04 11:56:27,381 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.py", line 460, in main
  File "awscli\customizations\commands.py", line 151, in __call__
  File "awscli\customizations\commands.py", line 205, in __call__
  File "awscli\customizations\configure\importer.py", line 95, in _run_main
  File "awscli\customizations\configure\importer.py", line 83, in _import_csv
  File "awscli\customizations\configure\importer.py", line 181, in parse_credentials
  File "awscli\customizations\configure\importer.py", line 164, in _parse_csv
  File "awscli\customizations\configure\importer.py", line 128, in _extract_expected_header_indices
awscli.customizations.configure.importer.CredentialParserError: Expected header "User Name" not found

Expected header "User Name" not found

### Reproduction Steps

Command:
aws configure import --profile-prefix TheUnderground --csv file://"C:\Clients\TheUnderground\Credentials\Setup\Setup.csv" --debug

C:\Clients\TheUnderground\Credentials\Setup\Setup.csv:
User Name,Password,Access key ID,Secret access key
Setup,,XX,XX

### CLI version used

aws-cli/2.11.0 Python/3.11.2 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 10.0.19041.2673

**Comment by aBurmeseDev** [comment]
Hi @gitaugakwa - thanks for reaching out. It sounds like you're missing `User Name` column in your CSV file. Could you edit the file and confirm if that fixes?

```
User Name,Access key ID,Secret access key
username,AKIAIOSFODNN7EXAMPLE,wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```
Best,
John

**Comment by robertdunaway** [comment]
John,

you are not seriously suggesting the above user doesn't know to check if they have a "User Name" header, are you?

That is not useful feelback.

I'm having the same problem and I see that many others are as well.  We all have the correct fields added with the correct case and spellings.

Something else is going on and the error message doesn't see me be helping.

This is all very frustrating.

**Comment by aBurmeseDev** [comment]
Hi @robertdunaway - thanks for checking in and sorry to hear that you're seeing similar issue. 

I still wasn't able to reproduce it on my end after creating new IAM and credentials for that user. However, one of my colleagues was able to reproduce similar error and he was able to resolve it by creating a new `.csv` file with same headers `User Name,Access key ID,Secret access key`. We believe there must have been text encoding issue with the existing file. 

Please let us know if the issue persists and we'd be more than happy to further assist you.

**Comment by assaflavi** [comment]
I'm running `aws-cli/2.10.3` on macOS, and having the same issue, despite the CSV appearing entirely valid.

Checked the file's encoding:
```bash
$ file accessKeys.csv
accessKeys.csv: Unicode text, UTF-8 (with BOM) text, with CRLF line terminators
```

The header seems fine:
```bash
$ head -n 1 accessKeys.csv
User Name,Access key ID,Secret access key
```

but when I run the `import` command with `--debug` this is the output:

```bash
$ aws configure --debug import --csv "file://accessKeys.csv"
2023-03-09 19:44:16,106 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.10.3 Python/3.11.2 Darwin/22.1.0 source/x86_64
2023-03-09 19:44:16,106 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', '--debug', 'import', '--csv', 'file://accessKeys.csv']
2023-03-09 19:44:16,130 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x106ecdee0>
2023-03-09 19:44:16,130 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x106a49260>
2023-03-09 19:44:16,130 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2023-03-09 19:44:16,131 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x1069bdda0>
2023-03-09 19:44:16,131 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x1069bf420>
2023-03-09 19:44:16,131 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x106ee1a80>
2023-03-09 19:44:16,131 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x106d50cc0>
2023-03-09 19:44:16,131 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2023-03-09 19:44:16,131 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x106ee0a40>
2023-03-09 19:44:16,131 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x106f88610>>
2023-03-09 19:44:16,131 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/data/cli.json
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x106e194e0>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x106e19800>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x106e19760>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x106e19940>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x106e198a0>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x106f85940>
2023-03-09 19:44:16,133 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.10.3 Python/3.11.2 Darwin/22.1.0 source/x86_64 prompt/off
2023-03-09 19:44:16,133 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', '--debug', 'import', '--csv', 'file://accessKeys.csv']
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x106eceac0>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1067022a0>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x106f3f740>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x1066d6980>
2023-03-09 19:44:16,133 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x1067642c0>
2023-03-09 19:44:16,140 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2023-03-09 19:44:16,147 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x106d504a0>
2023-03-09 19:44:16,147 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x106a3d260>
2023-03-09 19:44:16,147 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x106f3e660>
2023-03-09 19:44:16,147 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x106ee0a40>
2023-03-09 19:44:16,147 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x106f88610>>
2023-03-09 19:44:16,148 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_import: calling handler <function add_waiters at 0x106ee0a40>
2023-03-09 19:44:16,148 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_import: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x106f88610>>
2023-03-09 19:44:16,148 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.csv: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10672dcd0>
2023-03-09 19:44:16,149 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1064ae5d0>
2023-03-09 19:44:16,149 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.skip-invalid: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10672dcd0>
2023-03-09 19:44:16,149 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1064ae5d0>
2023-03-09 19:44:16,149 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.profile-prefix: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10672dcd0>
2023-03-09 19:44:16,149 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1064ae5d0>
2023-03-09 19:44:16,149 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 460, in main
    return command_table[parsed_args.command](remaining, parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/customizations/commands.py", line 151, in __call__
    return self._subcommand_table[subcommand_name](
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/customizations/commands.py", line 205, in __call__
    rc = self._run_main(parsed_args, parsed_globals)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/customizations/configure/importer.py", line 95, in _run_main
    self._import_csv(parsed_args.csv)
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/customizations/configure/importer.py", line 83, in _import_csv
    credentials = self._csv_parser.parse_credentials(contents)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/customizations/configure/importer.py", line 181, in parse_credentials
    parsed_rows = self._parse_csv(contents)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/customizations/configure/importer.py", line 164, in _parse_csv
    header_indices = self._extract_expected_header_indices(parsed_headers)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.3/libexec/lib/python3.11/site-packages/awscli/customizations/configure/importer.py", line 128, in _extract_expected_header_indices
    raise CredentialParserError(self._HEADER_NOT_FOUND % header)
awscli.customizations.configure.importer.CredentialParserError: Expected header "User Name" not found

Expected header "User Name" not found
```

**Comment by tim-finnigan** [comment]
This is strange - I was able to reproduce the issue, but found that the command worked after adding another column at the beginning of the CSV file resolved it. The error is getting raised [here in the code](https://github.com/aws/aws-cli/blob/c8670215858681483bbc37fca43f9cb345287691/awscli/customizations/configure/importer.py#L128), but that file hasn't been updated in ~2 years so I'm not sure what's going on, we will try to get some more information.

**Comment by lzholl** [comment]
Not sure how helpful this extra info is, but I changed the encoding from 'Unicode (UTF-8, with BOM)' to 'Unicode (UTF-8)' and that worked too.

**Comment by homerjam** [comment]
> Hi @gitaugakwa - thanks for reaching out. It sounds like you're missing `User Name` column in your CSV file. Could you edit the file and confirm if that fixes?
> 
> ```
> User Name,Access key ID,Secret access key
> username,AKIAIOSFODNN7EXAMPLE,wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
> ```
> 
> Best, John

Haha, imagine coming all this way and being flummoxed coming across the CSV format for the first time. I'm guessing an encoding issue

**Comment by tsengia** [comment]
I am experiencing the same issue, working on Windows 10.  
Doing `file -i accessKeys.csv` tells me that the charset is `utf-8`.
Opening in VSCode lists it as `utf8bom`, re-saving as plain `utf8` solves the issue.

**Comment by gitaugakwa** [comment]
> I am experiencing the same issue, working on Windows 10. Doing `file -i accessKeys.csv` tells me that the charset is `utf-8`. Opening in VSCode lists it as `utf8bom`, re-saving as plain `utf8` solves the issue.

This does in fact fix the issue. But does not resolve the problem. The csv was downloaded from the AWS IAM page and thus would expect the file to be compatible with the AWS CLI.

Either the CLI supports `utf8bom` or the Console downloads the file as `utf8`.

**Comment by dukesphere** [comment]
same, hours of just trying to get access. what a freaking joke

**Comment by tsengia** [comment]
> > I am experiencing the same issue, working on Windows 10. Doing `file -i accessKeys.csv` tells me that the charset is `utf-8`. Opening in VSCode lists it as `utf8bom`, re-saving as plain `utf8` solves the issue.
> 
> This does in fact fix the issue. But does not resolve the problem. The csv was downloaded from the AWS IAM page and thus would expect the file to be compatible with the AWS CLI.
> 
> Either the CLI supports `utf8bom` or the Console downloads the file as `utf8`.
> 
> 

Yes, you are correct. I should choose my words more carefully. Resaving as a different encoding does not fix the problem, however it is a temporary workaround.

**Comment by aBurmeseDev** [comment]
Thank you all for reporting. We totally understand your frustration and apologize for the inconvenience. I wanted to share that the team's aware of this behavior and will be looking into it. 

Meanwhile, please refer to one of these workarounds mentioned:
- change the encoding of the CSV file from `utf8bom` to `utf8` (**or**)
- re-save the file in a plain text editor with `User Name` header added

We'll keep it posted.

**Comment by svupper** [comment]
Hello I tried saving the .csv using vscode and UTF8 encoding and it doesn't help. I tried many solutions including the one you suggested aBurmeseDev but it doesn't work. Please help it's a bit urgent

**Comment by lzholl** [comment]
> I had to abandon the cvs file approach completely. Even if I did get it working, at this point I can't trust it in production. Nothing should be this buggy.
> 
> I am running my environment settings as part of the batch. I don't like it but the CLI simply doesn't read the file correctly that aws gives us. I can't trust it. Then support gaslights us. Nope... not trusting that.

??? They acknowledged the issue. Literally the opposite of gaslighting. There's really no need to be rude.

**Comment by robertdunaway** [comment]
The initial response is what I was referring to.  This problem was ignored until they were called out directly for dismissing it.  I wasn't trying to be rude.

**Comment by tim-finnigan** [comment]
This issue should now be fixed in CLI v2.11.4 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1). Please [update](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) your version of the CLI and let us know if you run into any further problems. I created another issue here for tracking the general issue of User Name missing by default: https://github.com/aws/aws-cli/issues/7753.

**Comment by krlinus** [comment]
There is positively no character encoding info in my csv file and I am having this issue. Just putting it out there. This version has quotation marks but the error is present for unquoted headers too:
$ od -xa awsprof2.csv
0000000    5522    6573    2072    614e    656d    2c22    4122    6363
          "   U   s   e   r  sp   N   a   m   e   "   ,   "   A   c   c
0000020    7365    2073    654b    2079    4449    2c22    5322    6365
          e   s   s  sp   K   e   y  sp   I   D   "   ,   "   S   e   c
0000040    6572    2074    6361    6563    7373    6b20    7965    0d22
          r   e   t  sp   a   c   c   e   s   s  sp   k   e   y   "  cr
0000060    6d0a    7579    6573    6e72    6d61    2c65    796d    6b61
         nl   m   y   u   s   e   r   n   a   m   e   ,   m   y   a   k
0000100    6469    6d2c    7379    6365    6572    0074
          i   d   ,   m   y   s   e   c   r   e   t
0000113

**Comment by rminkov** [comment]
I just ran into the same issue. I manually added the User Name column to the CSV file. Still getting the same error.

> aws configure import --csv file://C:\Users\user\Downloads\CLIUser_accessKeys.csv

Expected header "User Name" not found

> gc C:\Users\user\Downloads\CLIUser_accessKeys.csv | select -first 1
User Name,Access key ID,Secret access key

What is the solution?
It does not matter if I add "file://" or not - I get the same result. 
TIA.

**Comment by aBurmeseDev** [comment]
Hi @rminkov - which AWS CLI version are you using? If it's older than v2.11.4, please consider updating it as this was fixed in v2.11.4. Here's [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for your reference. There's also an existing [feature request](https://github.com/aws/aws-cli/issues/7753) with proposal to prompt the user if "User Name" is not found in CSV file to specify what they want their profile to be called.

Hope it helps!

**Comment by rminkov** [comment]
> Hi @rminkov - which AWS CLI version are you using? If it's older than v2.11.4, please consider updating it as this was fixed in v2.11.4. Here's [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for your reference. There's also an existing [feature request](https://github.com/aws/aws-cli/issues/7753) with proposal to prompt the user if "User Name" is not found in CSV file to specify what they want their profile to be called.
> 
> Hope it helps!

> aws --version
aws-cli/2.11.24 Python/3.11.3 Windows/10 exe/AMD64 prompt/off

**Comment by aBurmeseDev** [comment]
Thanks for reporting back. @rminkov. It's strange that you're still seeing this behavior. Have you tried one of these suggested workarounds:

- change the encoding of the CSV file from `utf8bom` to `utf8`
- re-save the file in a plain text editor with User Name header added

If the issue persists after trying workarounds, please submit a new issue with debug logs for us to investigate further.

Thanks again!

**Comment by rminkov** [comment]
> Thanks for reporting back. @rminkov. It's strange that you're still seeing this behavior. Have you tried one of these suggested workarounds:
> 
> * change the encoding of the CSV file from `utf8bom` to `utf8`
> * re-save the file in a plain text editor with User Name header added
> 
> If the issue persists after trying workarounds, please submit a new issue with debug logs for us to investigate further.
> 
> Thanks again!

Changing the encoding of the CSV file from utf8bom to utf8 worked. Thank you!

**Comment by kfirpeled** [comment]
> After wasting hours post updating to latest CLI version, I figured the command should be like below `aws configure import –csv file://credentials.csv/` I was missing the keyword "file://"

THANK YOU!!!

**Comment by renuspace** [comment]
Looks like special char was exist in the credential csv file downloaded from AWS Management console - in addition to that missing header **User Name** , which was causing the problem.

Refer below screenshot for details. These special char was not visible in notepad, but you can see in windows command line
![image](https://github.com/aws/aws-cli/assets/138312072/c4a2249e-de04-48bb-b915-f9b3ccc401de)

To resolve it.

Step:1
from windows command prompt notepad credentials.csv and add **User Name,Access key ID,Secret access key** on first line
and on 2nd line add username & associated credentials from originally downloaded file
Finally save it
![image](https://github.com/aws/aws-cli/assets/138312072/ecb3061e-781a-4936-a35d-01d4a4afa739)

Step:2
If you view the content of newly created file from windows command prompt , it should look similar to below screenshot without special char and with **User Name** header
![image](https://github.com/aws/aws-cli/assets/138312072/c0c37aaa-9a70-4d20-9ee2-d3d802da98c2)

Hope this helps, Thank you

**Comment by luffingfuture** [comment]
> After wasting hours post updating to latest CLI version, I figured the command should be like below `aws configure import –csv file://credentials.csv/` I was missing the keyword "file://"

This is actually the quickest fix... I have no idea why this is the case but it works.

**Comment by jeffbuzz** [comment]
Yes, adding the "file://" prefix to the actual file path on Windows gets past the header error.  But isn't this still a bug?  Why is this Linux "file://" syntax required on Windows?

This seems superfluous

`--csv file://"C:\users\jdoe\my.csv"`

**Comment by aguthrie19** [comment]
the problem still exists: special char as result of disagreement between (msi installed) aws cli decoding and access keys csv encoding (downloaded from aws management iam web console)

- system aws-cli/2.15.15 Python/3.11.6 Windows/10 exe/AMD64 prompt/off
- aws cli installed friom msi following: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#getting-started-install-instructions
- aws csv keys downloaded following: https://docs.aws.amazon.com/cli/latest/userguide/cli-authentication-user.html#cli-authentication-user-get


notice special char still exists
```
C:\Users\...>type mycli_accessKeys.csv
∩╗┐User Name,Access key ID,Secret access key
...
```

@lzholl's or @renuspace's solutions remain the quickest for me: reencode or recreate the file
> Not sure how helpful this extra info is, but I changed the encoding from 'Unicode (UTF-8, with BOM)' to 'Unicode (UTF-8)' and that worked too.

or

> To resolve it.
> 
> Step:1 from windows command prompt notepad credentials.csv and add **User Name,Access key ID,Secret access key** on first line and on 2nd line add username & associated credentials from originally downloaded file Finally save it ![image](https://private-user-images.githubusercontent.com/138312072/250288747-ecb3061e-781a-4936-a35d-01d4a4afa739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMTY0NzksIm5iZiI6MTcwNjMxNjE3OSwicGF0aCI6Ii8xMzgzMTIwNzIvMjUwMjg4NzQ3LWVjYjMwNjFlLTc4MWEtNDkzNi1hMzVkLTAxZDRhNGFmYTczOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwMDQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODdiODNlMGUzNjliNjM3NjEwNTdhMWY3M2I5MDc0YWI2NjE5YjA3NDhlNjEyNmE3ZWU1NDFhOWU0YmZjMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uge_uj825bKnp6Gnd3q7O-dtkiTiEP0lmq-klCVG_6s)

**Comment by ORUNSOLU** [comment]
This problem still persists as of today. Ubuntu 22.04 CLI  (aws-cli/2.15.32 Python/3.11.8 Linux/6.5.0-21-generic exe/x86_64.ubuntu.22 prompt/off)

Hello folks, I downloaded the `.csv` file to login but I also came across this issue. I tried the solution recommended by @aBurmeseDev which was to add the `User Name` column, which did not work out. I also checked the solution suggested by @izholl which suggested changing the encoding to UTF-8, this also did not resolve the issue.

**Comment by hamidrezasahraei** [comment]
I'm having this issue again on Macbook M1, Tried all of the workarounds too (Adding User Name header and changing encoding to UTF-8) but not been fixed.
version:
`aws-cli/2.17.32 Python/3.11.9 Darwin/23.3.0 source/arm64`

**Comment by emmanuelkaringi** [comment]
So, I encountered the same issue on **Ubuntu 22.04.5 LTS** and I fixed it by opening the csv file with VS Code (You can also use Vim or Nano). Add `User name,` and your username below it. Ensure you delete the BOM character and save the file. Rerun the AWS configuration command and **ensure you have three slashes after file**: `aws configure import --csv file:///home/user/Downloads/filename.csv`
