### ISSUE TITLE
Service Quotas for S3

### ISSUE THREAD

**Issue by jsoncow** [aws/aws-cli#7962]
### Describe the bug

 aws service-quotas list-service-quotas --service-code s3 returns empty.  This also returned empty for s3-outposts.

Additionally,  aws service-quotas get-service-quota --service-code s3 --quota-code L-DC2B2D3D returns `An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation:` (L-DC2B2D3D is the quota for S3 buckets)

### Expected Behavior

I expect to see service quotas returned for s3.

### Current Behavior

 aws service-quotas list-service-quotas --service-code s3 --profile <myprofile> --region us-east-1 returns 

{
    "Quotas": []
}

Other services worked (such as IAM)

### Reproduction Steps

 aws service-quotas list-service-quotas --service-code s3 --profile <myprofile> --region us-east-1

https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-service-quotas.html

### CLI version used

2.11.22

### Environment details (OS name and version, etc.)

MacOS Monterey 12.5.1

**Comment by aBurmeseDev** [comment]
Hi @jsoncow - thanks for reaching out. 
It appears that `--quota-code` is not available for [`list-service-quotas`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/service-quotas/list-service-quotas.html). If you're looking to get information about specific quota with quota-code flag, I'd recommend trying [`get-aws-default-service-quota`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/service-quotas/get-aws-default-service-quota.html).

As far as the empty output, can you confirm that you can see the service code in [AWS Console](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/service-quotas/get-aws-default-service-quota.html)?

**Comment by jsoncow** [comment]
Hi @aBurmeseDev - thanks for the response!  

To clarify, `list-service-quotas` works if I use `iam` for `--service-code but not `s3`.  Sorry, copied and pasted incorrectly - I fixed the comment above.  

The `-quota-code` was for `get-service-quota` which doesn't seem to work for S3 (such as S3 buckets).

**Comment by aBurmeseDev** [comment]
Thanks for following up @jsoncow!

In this case, I'm going to reach out to service team about this behavior on your behalf. Can you confirm one more thing that you can see the service quota in the AWS Console?

**Comment by rdob2022** [comment]
this is still an issue. I tried doing with AWS CLI v.2.13.26 and encountered empty quotas

**Comment by aBurmeseDev** [comment]
Hello @rdob2022 - sorry to hear that you're seeing this behavior. Can you please [open](https://github.com/aws/aws-cli/issues/new/choose) a new issue with specific to your workflow?

**Comment by rdob2022** [comment]
got it. created https://github.com/aws/aws-cli/issues/8238
