### ISSUE TITLE
aws ecr describe-repositories fails with linking error

### ISSUE THREAD

**Issue by codeimpossible** [aws/aws-cli#9433]
### Describe the bug

Our CI/CD pipeline began failing roughly when v2.26 was published with the following error:

```bash
[Publishing Runtime Image] Checking if ECR repository exists
[15:52:40][Publishing Runtime Image] less: /usr/local/aws-cli/v2/2.26.0/dist/libtinfo.so.5: no version information available (required by less)
[15:52:40][Publishing Runtime Image] 
[15:52:40][Publishing Runtime Image] less: Symbol `ospeed' has different size in shared object, consider re-linking
[15:52:40][Publishing Runtime Image] 
[15:52:40][Publishing Runtime Image] WARNING: terminal is not fully functional
```

The command we're running is `aws ecr describe-repositories --repository-names $service_lower --region us-east-1`

It seems the latest cli release may not have the correct dependencies?

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

For the command to work and return whether or not a repository exists.

### Current Behavior

It throws the exception mentioned and hangs, waiting for user input. 

### Reproduction Steps

run `aws ecr describe-repositories --repository-names <repo_name> --region us-east-1`

### Possible Solution

Revert to 2.25

### CLI version used

2.2.6

### Environment details (OS name and version, etc.)

ubuntu 20.x

**Comment by codeimpossible** [comment]
Our workaround ended up being to downgrade to v2.25.13

**Comment by hssyoo** [comment]
Thanks for opening this issue. Version 2.26.0 upgraded the bundled Python interpreter from 3.12 to 3.13. This caused the Linux installers to dynamically link `libtinfo.so.5`, which is bundled with the Linux installers.

Can you provide more details on the environment? Specifically, are there configurations set that may be changing dynamic linking behavior? Ubuntu is part of our build system's test matrix, I'm wondering what differences in the environment may be the cause.

**Comment by codeimpossible** [comment]
hi @hssyoo , I originally listed Ubuntu 20.x as the version our CI was running, but i was in the middle of firefighting and that's not correct. We run our CI in a containerized pipeline and the container this failed under is `ubuntu:18.04`. I've included the relevant lines from our dockerfile below.

```dockerfile
FROM ubuntu:18.04

## Install Wget, Gpg, Curl
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    wget \
    apt-transport-https ca-certificates curl \
    gnupg2 software-properties-common python unzip \
    rsync

## Install Docker
RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin \
    && docker --version || (echo "docker was not installed correctly!" && exit 1)

## Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && aws --version || (echo "aws cli was not installed correctly!" && exit 1)

## Install docker qemu-user-static for multi architecture support
RUN apt-get install -y qemu-user-static
```

The host machines for these containers are x86_64, but we use them to build multi-arch images, hence the install of qemu, but the rest of the system should be x86_64, so im not sure exactly what broke. Perhaps the older Ubuntu version is to blame?

**Comment by hssyoo** [comment]
@codeimpossible The fix was merged and released in the latest version (v2.26.2).

**Comment by curiousgg** [comment]
hey so @hssyoo i still get the error after setting `export AWS_PAGER=cat`, or where do i need to set it.

**Comment by hssyoo** [comment]
Hey @curiousgg, setting that environment variable in the runtime environment should work. We'd need some details to help narrow down the cause:
- Exact command being run
- Debug logs (append `--debug` to the failing AWS CLI command)
- Exact error
- Environment details (OS, architecture, etc)
- AWS CLI version
